version: "3.9"

services:
  vpnbot:
    build: .
    container_name: vpnbot_container

    env_file:
      - .env

    volumes:
      - ./database.db:/app/database.db
      - ./logs:/app/logs

    ports:
      - "${LK_PORT:-8080}:8080"

    restart: always